#! /usr/bin/python2.4
#
# rmtimequery: command line utility for ppfiletagger.query
# by pts@fazekas.hu at Sat Mar 20 13:03:26 CET 2010
#

if __name__ == '__main__':
  import logging
  import ppfiletagger.query
  import sys
  logging.BASIC_FORMAT = '[%(created)f] %(levelname)s %(message)s'
  logging.root.setLevel(logging.INFO)  # Prints INFO, but not DEBUG.
  sys.exit(ppfiletagger.query.main(sys.argv) or 0)
